export default [
  {
    poollink: 'https://cryptopools.aod-tech.com/',
    poolname: 'AOD-Tech Pools',
    hardfork: true,
    supportedAlgos: 'Scrypt, Groestl, Lyra2Rev2, Blake2s, x17',
  },
  {
    poollink: 'http://blockmasters.co',
    poolname: 'Block Masters',
    hardfork: false,
    supportedAlgos: 'Scrypt, Lyra2Rev2, x17',
  },
  {
    poollink: 'https://miningpoolhub.com/',
    poolname: 'Mining Pool Hub',
    hardfork: false,
    supportedAlgos: 'Scrypt',
  },
  {
    poollink: 'http://www.zpool.ca/site/mining',
    poolname: 'ZPool',
    hardfork: true,
    supportedAlgos: 'Scrypt, Groestl, Lyra2Rev2, Blake2s, x17',
  },
  {
    poollink: 'https://www.mining-dutch.nl',
    poolname: 'Mining Dutch',
    hardfork: true,
    supportedAlgos: 'Scrypt, Groestl, Blake2s, Lyra2Rev2, x17',
  },
  {
    poollink: 'http://xvg.mastermining.net/index.php?page=statistics&action=pool',
    poolname: 'MasterMining',
    hardfork: true,
    supportedAlgos: 'Scrypt',
  },
  {
    poollink: 'https://www.multipool.us/dashboard/pool/xvg',
    poolname: 'Multipool US',
    hardfork: false,
    supportedAlgos: 'Scrypt',
  },
  {
    poollink: 'http://zergpool.com/site/mining',
    poolname: 'ZergPool',
    hardfork: true,
    supportedAlgos: 'Scrypt, Groestl, Blake2s, Lyra2Rev2, x17',
  },
  {
    poollink: 'http://blazepool.com/',
    poolname: 'BlazePool',
    hardfork: false,
    supportedAlgos: 'Scrypt, Groestl, Blake2s, Lyra2Rev2, x17',
  },
  {
    poollink: 'http://poolovich.pro/',
    poolname: 'Poolovich',
    hardfork: false,
    supportedAlgos: 'Groestl, Lyra2Rev2, x17',
  },
  {
    poollink: 'http://xvg-mg.idcray.com/',
    poolname: 'IDcray',
    hardfork: false,
    supportedAlgos: 'Groestl, Lyra2Rev2',
  },
  {
    poollink: 'https://powermining.pw/',
    poolname: 'PowerMining',
    hardfork: true,
    supportedAlgos: 'Scrypt, Groestl, Lyra2Rev2, Blake2s, x17',
  },
  {
    poollink: 'http://verge.blake2s.com',
    poolname: 'Verge Blake2s',
    hardfork: true,
    supportedAlgos: 'Blake2s',
  },
  {
    poollink: 'http://nlpool.nl',
    poolname: 'NLpool',
    hardfork: true,
    supportedAlgos: 'Blake2s, x17',
  },
  {
    poollink: 'https://suprnova.cc/',
    poolname: 'suprnova.cc',
    hardfork: true,
    supportedAlgos: 'x17, Groestl, Lyra2Rev2',
  },
  {
    poollink: 'https://hash-to-coins.com/index.php',
    poolname: 'Hash to Coins',
    hardfork: false,
    supportedAlgos: 'Scrypt, x17, groestl, lyraRev2Re, Blake2s',
  },
  {
    poollink: 'https://prohashing.com/',
    poolname: 'ProHashing',
    hardfork: false,
    supportedAlgos: 'Scrypt, x17, groestl, lyraRev2Re, Blake2s',
  },
  {
    poollink: 'https://fairpool.pro',
    poolname: 'Fairpool.pro',
    hardfork: true,
    supportedAlgos: 'Scrypt, x17, groestl, lyraRev2Re, Blake2s',
  },
  {
    poollink: 'https://coinminerz.com/',
    poolname: 'CoinMinerz',
    hardfork: true,
    supportedAlgos: 'Scrypt',
  },
  {
    poollink: 'https://xvg.thecoin.pw/',
    poolname: 'TheCoin Pool',
    hardfork: true,
    supportedAlgos: 'Scrypt',
  },
  {
    poollink: 'https://www.f2pool.com/',
    poolname: 'F2Pool',
    hardfork: false,
    supportedAlgos: 'Scrypt, x17, groestl, lyraRev2Re, Blake2s',
  },
];
